spring:
  # JDBC
  datasource:
    driver-class-name: { Your database driver }
    url: { Your database url }
    username: { Your database username }
    password: { Your database password }

  # JPA
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: { Your database dialect }
        show_sql: true
        format_sql: true
        use_sql_comments: true

  # SQL
  sql:
    init:
      mode: always
      encoding: UTF-8
      schema-locations: classpath:schema.sql
